- block:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes

    - name: install git and make
      ansible.builtin.apt:
        name:
          - git
          - make

    - name: remove /tmp/qld-resources-prez directory if it exists
      ansible.builtin.file:
        path: /tmp/qld-resources-prez
        state: absent

    - name: clone qld-resources-prez repo to /tmp/qld-resources-prez
      ansible.builtin.git:
        repo: https://github.com/Kurrawong/qld-resources-prez-ui.git
        dest: /tmp/qld-resources-prez
        depth: 1

    - name: load initial fuseki data
      ansible.builtin.shell:
        chdir: /tmp/qld-resources-prez
        cmd: |
          podman build -f data-loader.Dockerfile -t data-loader .
          podman run --rm --name data-loader --network host -e FUSEKI_URL=http://0.0.0.0:3030 -e FUSEKI_USER={{ fuseki_user }} -e FUSEKI_PASSWORD={{ fuseki_password }} -v ./data_loading/create_fuseki_dataset.py:/app/create_fuseki_dataset.py -v ./data_loading/data_loader.py:/app/data_loader.py -v ./data_loading/entrypoint.sh:/app/entrypoint.sh -v ./data_loading/enable_union_default_graph.py:/app/enable_union_default_graph.py -v /fuseki-data:/fuseki data-loader

    - name: restart fuseki
      systemd:
        name: container-fuseki
        state: restarted
        enabled: true

  become: true
