- block:
    - name: populate service facts
      service_facts:

    - name: stop prez
      systemd:
        name: container-prez
        state: stopped
        daemon_reload: true
      when: "'container-prez.service' in services"

    - name: create prez container with a systemd service file managed by systemctl
      containers.podman.podman_container:
        name: prez
        image: "{{ prez_image }}"
        network: host
        entrypoint: /bin/bash
        command:
          - -c
          - uvicorn prez.app:app --host=0.0.0.0 --port=8000 --proxy-headers
        env:
          VOCPREZ_SPARQL_ENDPOINT: http://0.0.0.0:3030/gsq/sparql
          SPACEPREZ_SPARQL_ENDPOINT: http://0.0.0.0:3030/gsq/sparql
          VOCPREZ_SPARQL_UPDATE: http://0.0.0.0:3030/gsq/update
          SPACEPREZ_SPARQL_UPDATE: http://0.0.0.0:3030/gsq/update
          VOCPREZ_SPARQL_HTTP_STORE: http://0.0.0.0:3030/gsq/data
          SPACEPREZ_SPARQL_HTTP_STORE: http://0.0.0.0:3030/gsq/data
          VOCPREZ_SPARQL_USERNAME: "{{ fuseki_user }}"
          VOCPREZ_SPARQL_PASSWORD: "{{ fuseki_password }}"
        state: present
        generate_systemd:
          path: /etc/systemd/system/
          restart_policy: always

    - name: enable prez service
      systemd:
        name: container-prez
        enabled: true
        daemon_reload: true

    - name: start prez
      systemd:
        name: container-prez
        state: started
        daemon_reload: true

  become: true
